version: "3.7"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 35000:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: foglie-db
